# Generated by Django 5.2 on 2025-07-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_description_en_product_description_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Foto (nombre de archivo en static/images/)'),
        ),
    ]
